---
- name: slq-db-automation
  hosts: all
  become_method: runas
  tasks:
    - name: Create directory
      win_file:
        path: C:\sql_db
        state: directory
    - name: clean target directory
      win_shell: Remove-Item -path C:\sql_db\** -recurse
    - name: Download mysql-installer.msi from nexus
      win_get_url:
        url:  http://207.246.89.89:8081/repository/raw-hosted/mysql-installer-web-community-8.0.16.0.msi
        dest: C:\sql_db\
    - name: install mysql-installer.msi
      win_package:
        path: C:\sql_db\mysql-installer-web-community-8.0.16.0.msi
        state: present
        become: yes
        become_user: Administrator
    - name: install mysql-installer.msi    
      win_shell: C:\sql_db\mysql-installer-web-community-8.0.16.0.msi /quiet
    - name: Get all the services
      win_shell: Get-Service    
    - name: Check if a service is installed
      win_service:
        name: MySQL80
      register: service_info      
    #- name: start my-sql service
      #win_service:
        #name: MySQL80
        #state: restarted
    #- name: create a user-name for database
      #mysql_user:
        #name: DevOps-Mastro
        #password: test123
        #state: present
    #- name: create a new database
     # mysql_db:
      #  name: DevOps-Mastro
       # state: present              
